In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [2]:
data = load_breast_cancer()

In [3]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [4]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [6]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [7]:
pd.DataFrame(data['data'], columns = data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [8]:
pd.DataFrame(data['data'], columns = data['feature_names']).head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [9]:
data['target'].shape

(569,)

In [10]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [11]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [12]:
scaling = StandardScaler()

feature = scaling.fit_transform(data['data'])

In [13]:
pd.DataFrame(feature, columns = data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [14]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [15]:
pd.DataFrame(feature, columns = data['feature_names']).values

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [16]:
feature = data['data']

In [17]:
label = data['target']

In [18]:
feature.shape

(569, 30)

In [19]:
label.shape

(569,)

In [20]:
scale = StandardScaler()

feature = scale.fit_transform(feature)

In [22]:
j = 0
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [23]:
print(feature[568])
print(data['target_names'][label[568]],label[568])


[-1.80840125  1.22179204 -1.81438851 -1.34778924 -3.11208479 -1.15075248
 -1.11487284 -1.26181958 -0.8200699  -0.56103238 -0.07027874  0.3830925
 -0.15744905 -0.46615196  0.04934236 -1.16351619 -1.05750068 -1.91344745
  0.75282996 -0.382754   -1.41089258  0.76418957 -1.43273495 -1.07581292
 -1.85901852 -1.2075525  -1.30583065 -1.74506282 -0.04813821 -0.75120669]
benign 1


In [24]:
df_frt = pd.DataFrame(feature , columns = data['feature_names'])
df_lbl = pd.DataFrame(label , columns = ['label'])
df = pd.concat([df_frt, df_lbl], axis=1)
df = df.sample(frac = 1)

feature = df.values[ : , : 30]
label = df.values[ : ,30: ]

In [25]:
df

mean radius  mean texture  ...  worst fractal dimension  label
315    -0.465014     -0.567723  ...                -1.230554      1
36      0.034851      0.565559  ...                 0.967238      0
519    -0.391170     -0.602629  ...                 0.090005      1
104    -1.033042      0.000082  ...                -0.466924      1
523    -0.118517     -0.141869  ...                 0.352676      1
..           ...           ...  ...                      ...    ...
103    -1.207427      0.025680  ...                 0.052877      1
444     1.108425     -0.567723  ...                -0.093975      0
362    -0.388330     -0.104636  ...                -0.640929      1
277     1.329956      0.160649  ...                -1.472721      0
55     -0.740508     -0.125580  ...                -0.752869      1

[569 rows x 31 columns]

In [26]:
scaling = StandardScaler()

fit =  scaling.fit_transform(data['data'])

In [27]:
fit

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [28]:
# Training Data (500)
X_train = feature[ : 500]
y_train = data['target'][:500]

# Validationa Data (35)
X_val = feature[500 : 535]
y_val = data['target'][500:535]

# Test Data (34)
X_test = feature[535 : ]
y_test = data['target'][535: ]

In [29]:
model = Sequential()

model.add(Dense(32, activation = 'relu', input_dim = 30))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile( loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [30]:
model.fit( X_train , y_train, epochs = 10, batch_size = 5, validation_data = (X_val, y_val))

Epoch 1/10
100/100 [==============================] - 1s 5ms/step - loss: 0.6818 - accuracy: 0.6120 - val_loss: 0.6417 - val_accuracy: 0.7429
Epoch 2/10
100/100 [==============================] - 0s 3ms/step - loss: 0.6668 - accuracy: 0.6100 - val_loss: 0.6529 - val_accuracy: 0.7143
Epoch 3/10
100/100 [==============================] - 0s 3ms/step - loss: 0.6578 - accuracy: 0.6160 - val_loss: 0.6690 - val_accuracy: 0.6857
Epoch 4/10
100/100 [==============================] - 0s 3ms/step - loss: 0.6567 - accuracy: 0.6000 - val_loss: 0.6573 - val_accuracy: 0.7429
Epoch 5/10
100/100 [==============================] - 0s 3ms/step - loss: 0.6387 - accuracy: 0.6380 - val_loss: 0.6341 - val_accuracy: 0.7429
Epoch 6/10
100/100 [==============================] - 0s 3ms/step - loss: 0.6325 - accuracy: 0.6520 - val_loss: 0.7141 - val_accuracy: 0.6286
Epoch 7/10
100/100 [==============================] - 0s 3ms/step - loss: 0.5979 - accuracy: 0.6960 - val_loss: 0.7811 - val_accuracy: 0.5429
Epoch 

In [31]:
model.evaluate(X_test , y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.9165 - accuracy: 0.5294


[0.9164870381355286, 0.529411792755127]

In [32]:
model.evaluate(X_val , y_val)

2/2 [==============================] - 0s 10ms/step - loss: 0.9855 - accuracy: 0.4286


[0.9855479598045349, 0.4285714328289032]

In [33]:
for i in range(30):
  sample = X_test[i]
  sample = np.reshape(sample, (1,30))

  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-Malignant")

  if (y_test[i] == 1):
    print("*Benign")
  else:
    print("*Malignant")
  print("-----------")

-Malignant
*Malignant
-----------
-Malignant
*Malignant
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Malignant
*Benign
-----------
-Malignant
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Malignant
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Benign
-----------
-Benign
*Malignant
-----------
-Benign
*Malignant
-----------
-Malignant
*Malignant
-----------


In [34]:
t = 0
for i in y_val:
  if (i == 1):
    t += 1

print(t)

26


In [35]:
X_test[0] * -.1

array([ 0.13616469, -0.06167546,  0.13575892,  0.11117287,  0.02818352,
        0.09151856,  0.06131762,  0.09311407,  0.04367208, -0.04199496,
        0.03748961, -0.12013616,  0.03688271,  0.04945342, -0.12997264,
        0.03989473, -0.0267454 , -0.01660805, -0.20641102, -0.03132285,
        0.13303375,  0.01021394,  0.13225273,  0.10279977,  0.09673965,
        0.10896122,  0.09223646,  0.13546529,  0.07534906,  0.05550347])